function version = getFirmwareVersion(device)
%GETFIRMWAREVERSION Read firmware revision.

version = char( ...
    readCharacteristic( ...
        device, ...
        "180A", ...
        "2A26"));

version = strtrim(version);

end