function version = getHardwareVersion(device)
%GETHARDWAREVERSION Read hardware revision.

version = char( ...
    readCharacteristic( ...
        device, ...
        "180A", ...
        "2A27"));

version = strtrim(version);

end