function manufacturer = getManufacturerName(device)
%GETMANUFACTURERNAME Read manufacturer name.

manufacturer = char( ...
    readCharacteristic( ...
        device, ...
        "180A", ...
        "2A29"));

manufacturer = strtrim(manufacturer);

end