function serial = getSerialNumber(device)
%GETSERIALNUMBER Read device serial number.

serial = char( ...
    readCharacteristic( ...
        device, ...
        "180A", ...
        "2A25"));

serial = strtrim(serial);

end